name: Publish packages to PyPI

on:
  push:
    tags:
    - "*"

jobs:
  publish:
    name: Publish to PyPI
    runs-on: ubuntu-latest
    strategy:
      matrix:
        package: [api, core, schemas, decorators]
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: actions/setup-python@v5
        with:
          python-version: "3.12"
          cache: 'pip'
      - name: Install dependencies.
        run: |
          python -m pip install --upgrade pip build twine
      - name: Build and publish
        run: |
          cd ${{ matrix.package }}
          python -m build --sdist && python -m build --wheel
          twine upload dist/* -u __token__ -p ${{ secrets.PYPI_API_TOKEN }}
