name: Publish packages to PyPI

on:
    push:
        tags:
            - "*"
    workflow_dispatch:

jobs:
    publish:
        name: Publish to PyPI
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4
              with:
                  fetch-depth: 0

            - uses: actions/setup-python@v5
              with:
                  python-version: "3.12"
                  cache: "pip"

            - name: Install dependencies
              run: |
                  python -m pip install --upgrade pip build twine

            - name: Build and publish schemas
              id: publish_schemas
              run: |
                  cd schemas
                  python -m build --sdist && python -m build --wheel
                  twine upload dist/* -u __token__ -p ${{ secrets.PYPI_API_TOKEN }}

            - name: Build and publish core
              id: publish_core
              if: steps.publish_schemas.conclusion == 'success'
              run: |
                  cd core
                  python -m build --sdist && python -m build --wheel
                  twine upload dist/* -u __token__ -p ${{ secrets.PYPI_API_TOKEN }}

            - name: Build and publish client
              id: publish_client
              if: steps.publish_schemas.conclusion == 'success' && steps.publish_core.conclusion == 'success'
              run: |
                  cd client
                  python -m build --sdist && python -m build --wheel
                  twine upload dist/* -u __token__ -p ${{ secrets.PYPI_API_TOKEN }}

            - name: Build and publish api
              id: publish_api
              if: steps.publish_schemas.conclusion == 'success' && steps.publish_core.conclusion == 'success'
              run: |
                  cd api
                  python -m build --sdist && python -m build --wheel
                  twine upload dist/* -u __token__ -p ${{ secrets.PYPI_API_TOKEN }}

            - name: Build and publish decorators
              id: publish_decorators
              if: steps.publish_client.conclusion == 'success' && steps.publish_core.conclusion == 'success' && steps.publish_schemas.conclusion == 'success'
              run: |
                  cd decorators
                  python -m build --sdist && python -m build --wheel
                  twine upload dist/* -u __token__ -p ${{ secrets.PYPI_API_TOKEN }}
